services:
  # backend
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: fileserver-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/storage:/app/storage
      - ./backend:/app
    environment:
      - ENV=development
      - DEBUG=true
    networks:
      - fileserver-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: fileserver-frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend/src:/app/src
    networks:
      - fileserver-network
    depends_on:
      - backend

networks:
  fileserver-network:
    driver: bridge

